//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace start.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _118161182_future_retro_line_background_of_the_80s_vector_futuristic_synth_retro_wave_illustration_in_1980s_pos {
            get {
                object obj = ResourceManager.GetObject("118161182-future-retro-line-background-of-the-80s-vector-futuristic-synth-retro-w" +
                        "ave-illustration-in-1980s-pos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1a824c01b45ed566b1a887861843c55e {
            get {
                object obj = ResourceManager.GetObject("1a824c01b45ed566b1a887861843c55e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _472L6i {
            get {
                object obj = ResourceManager.GetObject("472L6i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f696d6167652e6962622e636f2f6336597a4b382f353731373637315f6f7269672e706e67 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f696d6167652e6962622e636f2f6336597a4b382f353731373637315f6f7269672" +
                        "e706e67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f636f6d626f62757273742d6672756974732e706e67 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f636f6d626f62757273742d6672756974732e706e67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f66727569742d6772617065732d6f7665726c61792e706e67 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f66727569742d6772617065732d6f7665726c61792e706e67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f66727569742d6772617065732d6f7665726c61792e706e671 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f66727569742d6772617065732d6f7665726c61792e706e671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f66727569742d6772617065732e706e67 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f66727569742d6772617065732e706e67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f66727569742d706561722d6f7665726c61792e706e67 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f66727569742d706561722d6f7665726c61792e706e67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f73752163617463682f696d672f66727569742d706561722d6f7665726c61792e706e671 {
            get {
                object obj = ResourceManager.GetObject("68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f536b696e6e696e672f6f737" +
                        "52163617463682f696d672f66727569742d706561722d6f7665726c61792e706e671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a4405e3b03ed493b76666bdf53029742 {
            get {
                object obj = ResourceManager.GetObject("a4405e3b03ed493b76666bdf53029742", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap áđá {
            get {
                object obj = ResourceManager.GetObject("áđá", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap đ {
            get {
                object obj = ResourceManager.GetObject("đ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doinayvuianghen {
            get {
                object obj = ResourceManager.GetObject("doinayvuianghen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hrjnfh {
            get {
                object obj = ResourceManager.GetObject("hrjnfh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kissclipart_corona_png_clipart_clip_art_56933e852fd1c3db {
            get {
                object obj = ResourceManager.GetObject("kissclipart-corona-png-clipart-clip-art-56933e852fd1c3db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kissclipart_electric_logo_png_clipart_electricity_electrical_e_bd404f699a04486b {
            get {
                object obj = ResourceManager.GetObject("kissclipart-electric-logo-png-clipart-electricity-electrical-e-bd404f699a04486b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ldsZak {
            get {
                object obj = ResourceManager.GetObject("ldsZak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ldsZak1 {
            get {
                object obj = ResourceManager.GetObject("ldsZak1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lef1 {
            get {
                object obj = ResourceManager.GetObject("lef1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lemon {
            get {
                object obj = ResourceManager.GetObject("lemon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miku1 {
            get {
                object obj = ResourceManager.GetObject("miku1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miku2 {
            get {
                object obj = ResourceManager.GetObject("miku2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap niodg {
            get {
                object obj = ResourceManager.GetObject("niodg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_the_crown_hotel_gold_crown_angle_king {
            get {
                object obj = ResourceManager.GetObject("png-clipart-the-crown-hotel-gold-crown-angle-king", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngguru_com {
            get {
                object obj = ResourceManager.GetObject("pngguru.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngguru1 {
            get {
                object obj = ResourceManager.GetObject("pngguru1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwave {
            get {
                object obj = ResourceManager.GetObject("pngwave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power_icon_png_25 {
            get {
                object obj = ResourceManager.GetObject("power-icon-png-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sf {
            get {
                object obj = ResourceManager.GetObject("sf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap silver {
            get {
                object obj = ResourceManager.GetObject("silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toppng_com_king_crown_transparent_500x420 {
            get {
                object obj = ResourceManager.GetObject("toppng.com-king-crown-transparent-500x420", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
